export const  tableDataList = [{
			goodsInfo: null,
			goodsName: '',
			goodsId: '',
			goodsSn: '',
			sizeList: [],
			sizeId: '',
			sizeName: '',
			quantity: 1,
			price: 0,
		},
		{
			goodsInfo: null,
			goodsName: '',
			goodsId: '',
			goodsSn: '',
			sizeList: [],
			sizeId: '',
			sizeName: '',
			quantity: 1,
			price: 0,
		},
		{
			goodsInfo: null,
			goodsName: '',
			goodsId: '',
			goodsSn: '',
			sizeList: [],
			sizeId: '',
			sizeName: '',
			quantity: 1,
			price: 0,
		},
		{
			goodsInfo: null,
			goodsName: '',
			goodsId: '',
			goodsSn: '',
			sizeList: [],
			sizeId: '',
			sizeName: '',
			quantity: 1,
			price: 0,
		},
		{
			goodsInfo: null,
			goodsName: '',
			goodsId: '',
			goodsSn: '',
			sizeList: [],
			sizeId: '',
			sizeName: '',
			quantity: 1,
			price: 0,
		},
		{
			goodsInfo: null,
			goodsName: '',
			goodsId: '',
			goodsSn: '',
			sizeList: [],
			sizeId: '',
			sizeName: '',
			quantity: 1,
			price: 0,
		}
	];